from django.contrib import admin
from.models import *

# Register your models here.
admin.site.register(Articulos)
admin.site.register(ArticulosCategoria)
admin.site.register(Bodega)
admin.site.register(Bodeguero)
admin.site.register(CabezaMovimiento)
admin.site.register(CategoriaBienes)
admin.site.register(CategoriaProductos)
admin.site.register(CategoriaServicios)
admin.site.register(CuerpoMovimiento)
admin.site.register(DescripcionPublicacion)
admin.site.register(Donativos)
admin.site.register(Kardex)
admin.site.register(Login)
admin.site.register(MetodoDePago)
admin.site.register(Paquetes)
admin.site.register(Personas)
admin.site.register(Publicaciones)
admin.site.register(Registro)
admin.site.register(Roles)
admin.site.register(TipoDeDocumento)
admin.site.register(TipoPublicacion)
admin.site.register(Usuarios)